tumblr_clone/account/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'


urlpatterns = [
    path('<slug:slug>',views.AccountIndex.as_view(),name='account_index'),
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='account/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('edit/<slug:slug>', views.UpdateUserView.as_view(),name='edit'),
    path('follow/<int:pk>',views.follow,name='follow'),
    path('unfollow/<int:pk>',views.unfollow,name='unfollow'),
    path('likes/<slug:slug>',views.LikeView.as_view(),name='likes'),
]

tumblr_clone/post/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'post'


urlpatterns = [
    path('create',views.CreatePost.as_view(),name='create'),
    path('view/<username>/<int:pk>',views.PostDetail.as_view(),name='detail'),
    path('dashboard',views.Dashboard.as_view(),name='dashboard'),
    path('delete/<int:pk>',views.PostDelete.as_view(),name='delete'),
    path('edit/<int:pk>',views.EditPost.as_view(),name='edit'),
    path('view/<username>',views.UserPosts.as_view(),name='user_posts'),
    path('like/<int:pk>',views.like,name='like'),
    path('unlike/<int:pk>',views.unlike,name='unlike'),
    path('reblog/<int:pk>',views.ReblogPost.as_view(),name='reblog'),
    path('add_note/<int:pk>',views.AddNote.as_view(),name='add_note'),
    path('note_list/<int:pk>',views.NotesList.as_view(),name='note_list'),
]

tumblr_clone/tumblr_clone/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from . import settings
import debug_toolbar


from post import views as post_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='index'),
    path('account/',include('account.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.LoginPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('post/',include('post.urls')),
    path('dashboard',post_view.Dashboard.as_view(),name='dashboard'),
    path('__debug__/', include(debug_toolbar.urls)),
    path('message/',include('messaging.urls'),name='message'),
    path('search/',views.SearchPage.as_view(),name='search'),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tumblr_clone/post/models.py
from django.db import models
from django.urls import reverse
from account.models import User
from taggit.managers import TaggableManager
from django.utils import timezone
# Create your models here.
class Post(models.Model):
    POST_TYPE_CHOICES = [
    ('TXT','Text'),
    ('Q','Quote'),
    ('IMG','Image'),
    ('VID','Video'),
    ('GIF','GIF'),
    ('AUD','Audio'),
    ]
    POST_WHEN_CHOICES = [
        ('NOW','Post Now'),
        ('QU','Add to queue'),
        ('DR','Add to draft'),
        ('PR','Post privately'),
        ('SC','Schedule'),
    ]
    post_type = models.CharField( max_length=3,choices=POST_TYPE_CHOICES,default='TXT')
    title = models.CharField(max_length=128,default=' ')
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to='post/images/',blank=True,null=True)
    video = models.FileField(upload_to='post/videos/',blank=True,null=True)
    gif = models.FileField(upload_to='post/gifs/',blank=True,null=True)
    audio = models.FileField(upload_to='post/audio/',blank=True,null=True)
    op = models.ForeignKey(User,on_delete=models.CASCADE,related_name='posts')
    is_reblogged = models.BooleanField(default=False,blank=True)
    tags = TaggableManager(blank=True)#to manage tagging
    posted_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)
    source = models.URLField(blank=True)
    quote_text = models.TextField(blank=True)
    post_when = models.CharField(max_length=3,choices=POST_WHEN_CHOICES,default='NOW')
    scheduled_date = models.DateTimeField(blank=True,null=True)
    likes = models.ManyToManyField(User, through='Like',related_name='liked_posts')
    reblogs = models.ManyToManyField(User, through='Reblog',through_fields=('reblogged_content','reblogged_from'),related_name='reblogged_posts')
    notes = models.ManyToManyField(User, through='Note',related_name='post_noted')

    class Meta:
        ordering = ['-modified_on']

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("post:detail",kwargs={"username":self.op.username,"pk":self.pk})

#defining the relations
class Note(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    note = models.TextField()



class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    liked_on = models.DateTimeField(auto_now=True)
    class Meta:
        unique_together = [['post','user']]#so that a user cannot like a post more than once
        ordering = ['-liked_on']#ordering on liked on so it is returned in descending order


class Reblog(models.Model):
    reblogged_from = models.ForeignKey(User,on_delete=models.CASCADE)#parent_post.op
    parent_post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='parent_of')
    reblogged_content = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='reblogged_content')
    def __str__(self):
        return 'reblog | '+str(self.id)

from django.db.models.signals import post_save
def add_reblogged_from(sender, instance, **kwargs):
   instance.reblogged_from = instance.parent_post.op
   #instance.save()
post_save.connect(add_reblogged_from, sender=Reblog)

tumblr_clone/post/forms.py
from django.forms import ModelForm
from .models import Post

class NewPostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ['modified_on','op','is_reblogged']

tumblr_clone/post/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import CreateView,TemplateView,UpdateView,ListView,DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy,reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
#from braces.views import SelectRelatedMixin
User = get_user_model()
from .models import Post,Reblog,Note
# Create your views here.


# CREATING A POST
#   queuing it
#   scheduling it
#   drafting it
class CreatePost(CreateView,LoginRequiredMixin):
    model = Post
    fields = ['post_type','title','text','image','video','gif','audio','tags','source','quote_text','post_when','scheduled_date']
    template_name = 'post/new_post.html'
    success_url = reverse_lazy('dashboard')
    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.op = self.request.user#adding the op as the one creating the post
        self.object.save()
        return super().form_valid(form)

#DASHBOARD
class Dashboard(ListView,LoginRequiredMixin):
    model = Post
    template_name = 'post\dashboard.html'
    paginate_by = 20
    context_object_name = 'posts'

    def get_queryset(self):
        u =self.request.user
        following_users = u.is_followed_by.all()
        follow_posts = Post.objects.all().filter(op__in=following_users)
        return follow_posts


#VIEW POST DETAILS

class PostDetail(DetailView):
    model = Post
    template_name = 'post\detail.html'


# DELETING A POST

class PostDelete(DeleteView,LoginRequiredMixin):
    model = Post
    template_name = 'post\post_delete.html'
    success_url = reverse_lazy('dashboard')
    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

# EDITING A POST
class EditPost(LoginRequiredMixin,UpdateView):
    model = Post
    fields = ['post_type','title','text','image','video','gif','audio','tags','source','quote_text']
    template_name = 'post\edit_post.html'
    slug_field = 'pk'

    def get_success_url(self,*args,**kwargs):
        return reverse_lazy('post:detail',kwargs={'username':self.request.user.username,'pk':self.object.pk})






# LIKING A POST
def like(request,pk):
    post_to_be_liked = get_object_or_404(Post,id=request.POST.get('post_like'))
    post_to_be_liked.likes.add(request.user)
    next = request.POST.get('next','/')
    #adding to notes
    like_note = Note.objects.create(post=post_to_be_liked,user=request.user,note='LIKED')
    return HttpResponseRedirect(next)
#UNLIKING A POST
def unlike(request,pk):
    post_to_be_unliked = get_object_or_404(Post,id=request.POST.get('post_unlike'))
    post_to_be_unliked.likes.remove(request.user)
    next = request.POST.get('next','/')
    #removing from NOTES
    note_unlike = Note.objects.get(post=post_to_be_unliked,note='LIKED',user=request.user)
    note_unlike.delete()
    return HttpResponseRedirect(next)

#  https://www.youtube.com/watch?v=PXqRPqDjDgc
#USER POSTS
class UserPosts(ListView,LoginRequiredMixin):
    model = Post
    template_name = 'post/user_post.html'
    paginate_by = 20
    context_object_name = 'user_posts'

    def get_queryset(self):
        self.username = get_object_or_404(User,username=self.kwargs['username'])
        all_posts = Post.objects.all().filter(op__exact=self.username)
        return all_posts

# REBLOGGING A POST
class ReblogPost(CreateView,LoginRequiredMixin):
    model = Post
    fields = ['post_type','title','text','image','video','gif','audio','tags','source','quote_text','post_when','scheduled_date']
    template_name = 'post/reblog_post.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.op = self.request.user#adding the op as the one creating the post
        self.object.is_reblogged = True
        parent_post = Post.objects.get(pk=self.kwargs['pk'])
        self.object.text = parent_post.text + '<hr>' + self.object.text
        self.object.image = parent_post.image
        self.object.save()
        self.object.reblogs.add(parent_post.op,through_defaults={'parent_post':parent_post})
        reblog_note = Note.objects.create(post=parent_post,user=self.request.user,note=self.object.text)
        self.object.save()
        return super().form_valid(form)
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        parent_post = Post.objects.get(pk=self.kwargs['pk'])
        context['parent_post'] = parent_post#adding the context so it can be displayed with the form
        return context
#ADDING NOTES TO A POST

class AddNote(CreateView,LoginRequiredMixin):
    model = Note
    fields = ['note']
    success_url = reverse_lazy('dashboard')
    template_name = 'post/add_note.html'

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        post_to_add_note = Post.objects.get(pk=self.kwargs['pk'])
        self.object.post = post_to_add_note
        self.object.save()
        return super().form_valid(form)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        post_to_add_note = Post.objects.get(pk=self.kwargs['pk'])
        context['post'] = post_to_add_note #adding the context so it can be displayed with the form
        return context
#ALL NOTES FOR POST
class NotesList(ListView,LoginRequiredMixin):
    model = Note
    template_name = 'post/all_notes.html'
    context_object_name = 'post_notes'

    def get_queryset(self,**kwargs):
        post_notes = Note.objects.all().select_related('post').filter(post__pk__iexact=self.kwargs['pk'])
        return post_notes

tumblr_clone/post/templates/post/_post.html
<div class="container">
  <!--PRE-POST-->
  <div class="pre-post">
    {% if post.is_reblogged == True %}
      <span><a class="post-op" href='{% url "account:account_index" slug=post.op.slug %}'><b>{{post.op}}</b></a>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-repeat" viewBox="0 0 16 16">
          <path d="M11.534 7h3.932a.25.25 0 0 1 .192.41l-1.966 2.36a.25.25 0 0 1-.384 0l-1.966-2.36a.25.25 0 0 1 .192-.41zm-11 2h3.932a.25.25 0 0 0 .192-.41L2.692 6.23a.25.25 0 0 0-.384 0L.342 8.59A.25.25 0 0 0 .534 9z"/>
          <path fill-rule="evenodd" d="M8 3c-1.552 0-2.94.707-3.857 1.818a.5.5 0 1 1-.771-.636A6.002 6.002 0 0 1 13.917 7H12.9A5.002 5.002 0 0 0 8 3zM3.1 9a5.002 5.002 0 0 0 8.757 2.182.5.5 0 1 1 .771.636A6.002 6.002 0 0 1 2.083 9H3.1z"/>
        </svg>
        {% for reblog in post.reblogs.all|slice:":1" %}
          <a class='post-reblogged_from' href='{% url "account:account_index" slug=reblog.slug %}'><b> {{reblog.username}}</b></a>
        {% endfor %}

      </span>
      {% else %}
        <a class="post-op" href='{% url "account:account_index" slug=post.op.slug %}'><b>{{post.op}}</b></a>
    {% endif %}
    <hr>
  </div>
  <!--POST-->
  <div class="actual-post" style="border:2px;color:#333">
    {% if post.post_type == 'TXT' %}
      <a href="{% url 'post:detail' username=user pk=post.pk %}"> <h3>{{post.title}}</h3></a>
      {% if post.image %}
        <img src="{{ post.image.url }}" height="40%" width ="40%">
      {% endif %}
    {% elif post.post_type == 'Q' %}
      <span class="post-quote">{{post.quote_text|safe}}</span>
      {% elif post.post_type == 'IMG' %}
        {% if post.image %}
          <img src="{{ post.image.url }}" height="40%" width ="40%">
        {% endif %}
      {% elif post.post_type == 'VID' %}
        {% if post.video %}
          <video height="40%" width ="40%" controls>
            <source src="{{ post.video.url }}" type="video/">
          </video>
        {% endif %}
    {% endif %}
    <span class="post-quote">{{post.text|safe}}</span><p></p>
    <hr>
  </div>
  <!--POST FOOTER-->
  <div class="post-footer">
    {% comment %}TAGS{% endcomment %}
    <div class="post-tags">
      <p>tags: {{post.tags.all|join:","}}</p>
    </div>
    {% if post.op == user and user.is_authenticated %}

    {% comment %}EDIT{% endcomment %}
      <a href="{% url 'post:edit' post.pk %}" class="btn">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
          <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
        </svg>
      </a>
  {% comment %}DELETE{% endcomment %}
      <a href="{% url 'post:delete' post.pk %}" class="btn">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
          <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
        </svg>
      </a>
    {% endif %}
    {% comment %}LIKE/UNLIKE{% endcomment %}
    {% if request.user in post.likes.all %}
      <form class="unlike-form" action="{% url 'post:unlike' post.pk %}" method="post">
        {%csrf_token%}
        <input type="hidden" name="next" value="{{ request.path }}">
        <button class="btn" type="submit" id="unlike_button" name="post_unlike" value={{post.pk}}>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
          </svg>
        </button>
      </form>
      {% else %}
      <form class="like-form" action="{% url 'post:like' post.pk %}" method="post">
        {%csrf_token%}
        <input type="hidden" name="next" value="{{ request.path }}">
        <button class="btn" type="submit" id="like_button" name="post_like" value={{post.pk}}>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
            <path d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
          </svg>
        </button>
      </form>
    {% endif %}
    {% comment %}see notes{% endcomment %}
    <a href="{% url 'post:note_list' pk=post.pk %}">{{post.notes.count}} Notes</a>
  {% comment %}REBLOG{% endcomment %}
    <a href="{% url 'post:reblog' post.pk %}" class="btn" id="reblog_button">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-repeat" viewBox="0 0 16 16">
        <path d="M11.534 7h3.932a.25.25 0 0 1 .192.41l-1.966 2.36a.25.25 0 0 1-.384 0l-1.966-2.36a.25.25 0 0 1 .192-.41zm-11 2h3.932a.25.25 0 0 0 .192-.41L2.692 6.23a.25.25 0 0 0-.384 0L.342 8.59A.25.25 0 0 0 .534 9z"/>
        <path fill-rule="evenodd" d="M8 3c-1.552 0-2.94.707-3.857 1.818a.5.5 0 1 1-.771-.636A6.002 6.002 0 0 1 13.917 7H12.9A5.002 5.002 0 0 0 8 3zM3.1 9a5.002 5.002 0 0 0 8.757 2.182.5.5 0 1 1 .771.636A6.002 6.002 0 0 1 2.083 9H3.1z"/>
      </svg>
    </a>
    {% comment %}ADD NOTE{% endcomment %}
      <a href="{% url 'post:add_note' post.pk %}" class="btn" id="reblog_button">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
          <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
        </svg>
      </a>
  </div>
</div>
<hr style="height:1px;border:none;color:#333;background-color:#333;">

tumblr_clone/post/templates/post/add_note.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <h2>Add a note to the post</h2>
    <div class="container post-to-add-note">
      {% include "post/_post.html" with post=post %}
    </div>
    <div class="container add-note-form">
      <form class="add-note" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Add note" class="btn btn-primary">
        <a href="{% url 'dashboard' %}" class="btn btn-outline-danger">Cancel</a>
      </form>
    </div>
  </div>
{% endblock content %}

tumblr_clone/post/templates/post/all_notes.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <h4>{{post_notes.count}} notes</h4>
    {% for notes in post_notes %}
      <hr>
      <h4><a href="{% url 'account:account_index' notes.user.slug %}">{{notes.user}}</a></h4>
      <span>{{notes.note|safe}}</span>
      <hr>
    {% endfor %}
    {% for notes in post_notes|slice:":1"  %}
      <a href="{% url 'post:add_note' notes.post.pk %}" class="btn btn-primary">Add a note here</a>
    {% endfor %}
  </div>
{% endblock content %}

tumblr_clone/post/templates/post/dashboard.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    {% for post in posts  %}
      <div class="container">
        {% include "post\_post.html" %}
      </div>
    {% endfor %}
  </div>
{% endblock content %}

tumblr_clone/post/templates/post/detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    {% include "post/_post.html" %}
  </div>
{% endblock content %}

tumblr_clone/post/templates/post/edit_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="container">
    <h2>Edit your post</h2>
    <form class="post-edit" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form | crispy}}
      <input type="submit" value="Post" class="btn btn-outline-primary">
      <a href="{% url 'post:dashboard' %}">Cancel</a>
    </form>
  </div>
{% endblock content %}

tumblr_clone/post/templates/post/new_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="container">
    <h2>Create a new post!</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" class="btn btn-primary" value="Post">
      <a href="{% url 'dashboard' %}" class="btn btn-outline-danger">Cancel</a>
    </form>
  </div>
{% endblock content %}

tumblr_clone/post/templates/post/post_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>tumblr</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>
    {% block content %}

    {% endblock content %}

  </body>
</html>

tumblr_clone/post/templates/post/post_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container post">
    <h3>Are you sure you want to whoosh away this post?</h3>
    {% include "post/_post.html" with post=object %}
    <form class="delet-post" method="post">
      {% csrf_token %}
      <input type="submit" value="confirm Delete" class="btn btn-outline-danger">
      <a href="{% url 'post:dashboard' %}" class="btn btn-simple btn-large btn-default">Cancel</a>
    </form>
  </div>

{% endblock content %}

tumblr_clone/post/templates/post/reblog_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="container">
    <h2>Reblog a post</h2>
    <div class="container parent_post-content">
      {% include "post/_post.html" with post=parent_post %}
      <hr>
    </div>
    <form class="reblog-post" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form | crispy}}
      <input type="submit" class="btn btn-success" value="Reblog">
      <a href="{% url 'dashboard' %}" class="btn btn-outline-danger">Cancel</a>
    </form>
  </div>
{% endblock content %}

tumblr_clone/post/templates/post/user_post.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div class="row">
      {% for post in user_posts  %}
        {% include "post\_post.html"%}
      {% endfor %}
    </div>
  </div>
{% endblock content %}