tumblr_clone/messaging/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'message'

urlpatterns = [
    path('conversations/', views.Converstaions.as_view(),name='conversations'),
    path('messages/<int:pk>',views.AllMessagesByUser.as_view(),name='user_list'),
]

tumblr_clone/post/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'post'


urlpatterns = [
    path('create',views.CreatePost.as_view(),name='create'),
    path('view/<username>/<int:pk>',views.PostDetail.as_view(),name='detail'),
    path('dashboard',views.Dashboard.as_view(),name='dashboard'),
    path('delete/<int:pk>',views.PostDelete.as_view(),name='delete'),
    path('edit/<int:pk>',views.EditPost.as_view(),name='edit'),
    path('view/<username>',views.UserPosts.as_view(),name='user_posts'),
    path('like/<int:pk>',views.like,name='like'),
    path('unlike/<int:pk>',views.unlike,name='unlike'),
    path('reblog/<int:pk>',views.ReblogPost.as_view(),name='reblog'),
    path('add_note/<int:pk>',views.AddNote.as_view(),name='add_note'),
    path('note_list/<int:pk>',views.NotesList.as_view(),name='note_list'),
]

tumblr_clone/tumblr_clone/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from . import settings
import debug_toolbar


from post import views as post_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='index'),
    path('account/',include('account.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.LoginPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('post/',include('post.urls')),
    path('dashboard',post_view.Dashboard.as_view(),name='dashboard'),
    path('__debug__/', include(debug_toolbar.urls)),
    path('message/',include('messaging.urls'),name='message'),
    path('search/',views.SearchPage.as_view(),name='search'),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tumblr_clone/messaging/models.py
from django.db import models
from django.urls import reverse
from account.models import User
from django.utils import timezone
# Create your models here.

class Message(models.Model):
    sender = models.ForeignKey(User,on_delete=models.CASCADE,related_name='sender')
    receiver = models.ForeignKey(User,on_delete=models.CASCADE,related_name='receiver')
    message = models.TextField()
    sent_on = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-sent_on']
    def __str__(self):
        return str(self.sender) + ' > ' + str(self.receiver)+' '+str(self.pk)
    def get_absolute_url(self):
        return reverse("message:list")

tumblr_clone/messaging/views.py
from django.db.models import Q

# Create your views here.
from django.shortcuts import render,get_object_or_404
from django.views.generic import CreateView,TemplateView,UpdateView,ListView,DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy,reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Message
from account.models import User

class AllMessagesByUser(CreateView,LoginRequiredMixin):
    model = Message
    template_name = 'messaging/allmessages.html'
    fields = ['message']
    success_url = reverse_lazy('message:conversations')

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        user1 = self.request.user
        user2 = User.objects.get(pk=self.kwargs['pk'])
        context['user_messages'] = Message.objects.all().filter((Q(sender__exact=user1) & Q(receiver__exact=user2)) | (Q(sender__exact=user2) & Q(receiver__exact=user1)))
        return context
    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.sender = self.request.user#adding the op as the one creating the post
        self.object.receiver = User.objects.get(pk=self.kwargs['pk'])
        self.object.save()
        return super().form_valid(form)


class Converstaions(ListView):
    model = Message
    template_name = 'messaging/conversations.html'
    context_object_name = 'users'
    paginate_by = 40

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        users_interacted_with = set()
        all_messages = Message.objects.filter(Q(sender=self.request.user) | Q(receiver=self.request.user))
        for message in all_messages:
            if(message.sender==self.request.user):
                users_interacted_with.add(message.receiver)
            else:
                users_interacted_with.add(message.sender)
        context['interacted_users'] = users_interacted_with
        return context

tumblr_clone/messaging/templates/messaging/allmessages.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container">
  {% for message in user_messages %}
    {% if message.sender == request.user %}
      <div class="user-sent" style="background-color:white;color:black;align-items:right">
        <h4 class='message-sender' style="border-bottom:2px;padding:3px">{{message.sender.username}}</h4>
        <span class='message' style="align:right">{{message.message|safe}}</span>
        <p><small>{{message.sent_on}}</small></p>
      </div>
      {% else %}
      <div class="user-received" style="background-color:#598ade;color:black;align-items:left">
        <h4 class='message-sender' style="border-bottom:2px;padding:3px">{{message.sender.username}}</h4>
        <span class='message' style="align:left">{{message.message|safe}}</span>
        <p><small>{{message.sent_on}}</small></p>
      </div>
    {% endif %}
    <hr>
  {% endfor %}
  <form class="messaging" method="post">
    {%csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Send" class="btn btn-primary">
  </form>
</div>
{% endblock content %}

tumblr_clone/messaging/templates/messaging/conversations.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  {% for conversers in interacted_users %}
        <div class="container converation">
          {% if conversers.profile_picture %}<img src="{{conversers.profile_picture.url}}" width="10%" height="10%">{% endif %}
          <span class="username-link"><p><a href="{% url 'message:user_list' conversers.pk %}">{{conversers}}</a></p> </span>
          {% comment %}
            <span class="message-preview"><small>{{conversers.message}}</small></span>
          {% endcomment %}
        </div
      <hr>
  {% endfor %}
</div>
<style>

</style>
{% endblock content %}